version: '3.4'

services:
  client:
    container_name: jadeocr_client
    image: client
    build:
      context: ./client
      args:
        API_BASEURL: ${VUE_APP_API_BASEURL}
    ports:
      - 8085:80
  server:
    container_name: jadeocr_server
    image: server
    build:
      context: ./server
    environment:
      NODE_ENV: production
      MONGOOSEURL: ${MONGOOSEURL}
    ports:
      - 3000:3000
